export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
export const DELETE_SINGLE_CONTACT = 'DELETE_SINGLE_CONTACT';
export const EDIT_SINGLE_CONTACT = 'EDIT_SINGLE_CONTACT';